In [48]:
# import course;course.header()
import pandas as pd
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.io as pio
pio.renderers.default = "browser"

### Read the arabica data set into a dataframe
You will notice an "Unnamed: 0" column. Where does it come from, how can one get "rid" of it?

## Drop some categorical columns
The dataset is rich in meta data, however we just want to keep "Country.of.Origin", "Producer", "Processing.Method". How to drop the rest?
While you're at it rename the three columns we want to keep so they do not have dots but space in their name.

## Clean the data set
The dataset does not seem to be as clean as the filename might suggest. How can you get a quick overview over the data and identify which columns have extreme outliers? If you cannot using pd commands, try to plot (see next question)!

## Plot 
Plot a plotly histogram for each of the remaining columns. Can you write a loop?

## cleaning outliers
* define heuristics that classify outliers for each column
* set outliers to median

## Identify 
 * Which countries have more than 10 and less than 30 entries?
 * Which is the producer with most entries?
 * What is the mosts common and least common "Processing Method"

In [21]:
df = pd.read_csv('../data/arabica_data_cleaned.csv')
df.head()

,Unnamed: 0,Species,Owner,Country.of.Origin,Farm.Name,Lot.Number,Mill,ICO.Number,Company,Altitude,Region,Producer,Number.of.Bags,Bag.Weight,In.Country.Partner,Harvest.Year,Grading.Date,Owner.1,Variety,Processing.Method,Aroma,Flavor,Aftertaste,Acidity,Body,Balance,Uniformity,Clean.Cup,Sweetness,Cupper.Points,Total.Cup.Points,Moisture,Category.One.Defects,Quakers,Color,Category.Two.Defects,Expiration,Certification.Body,Certification.Address,Certification.Contact,unit_of_measurement,altitude_low_meters,altitude_high_meters,altitude_mean_meters
0,1,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,guji-hambela,METAD PLC,300,60 kg,METAD Agricultural Development plc,2014,"April 4th, 2015",metad plc,NaN,Washed / Wet,8.67,8.83,8.67,8.75,8.50,8.42,10.0,10.0,10.0,8.75,90.58,0.12,0,0.0,Green,0,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0
1,2,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,guji-hambela,METAD PLC,300,60 kg,METAD Agricultural Development plc,2014,"April 4th, 2015",metad plc,Other,Washed / Wet,8.75,8.67,8.50,8.58,8.42,8.42,10.0,10.0,10.0,8.58,89.92,0.12,0,0.0,Green,1,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0
2,3,Arabica,grounds for health admin,Guatemala,"san marcos barrancas ""san cristobal cuch",NaN,NaN,NaN,NaN,1600 - 1800 m,NaN,NaN,5,1,Specialty Coffee Association,NaN,"May 31st, 2010",Grounds for Health Admin,Bourbon,NaN,8.42,8.50,8.42,8.42,8.33,8.42,10.0,10.0,10.0,9.25,89.75,0.00,0,0.0,NaN,0,"May 31st, 2011",Specialty Coffee Association,36d0d00a3724338ba7937c52a378d085f2172daa,0878a7d4b9d35ddbf0fe2ce69a2062cceb45a660,m,1600.0,1800.0,1700.0
3,4,Arabica,yidnekachew dabessa,Ethiopia,yidnekachew dabessa coffee plantation,NaN,wolensu,NaN,yidnekachew debessa coffee plantation,1800-2200,oromia,Yidnekachew Dabessa Coffee Plantation,320,60 kg,METAD Agricultural Development plc,2014,"March 26th, 2015",Yidnekachew Dabessa,NaN,Natural / Dry,8.17,8.58,8.42,8.42,8.50,8.25,10.0,10.0,10.0,8.67,89.00,0.11,0,0.0,Green,2,"March 25th, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1800.0,2200.0,2000.0
4,5,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,guji-hambela,METAD PLC,300,60 kg,METAD Agricultural Development plc,2014,"April 4th, 2015",metad plc,Other,Washed / Wet,8.25,8.50,8.25,8.50,8.42,8.33,10.0,10.0,10.0,8.58,88.83,0.12,0,0.0,Green,2,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0

In [58]:
renamed_df = df[['Country.of.Origin', 'Producer', 'Processing.Method']].copy()
renamed_df.rename(columns={
    'Processing.Method': 'Processing method',
    'Country.of.Origin': 'Country of origin'},
                  inplace=True)

In [51]:
def generate_plot(df, column):   
    data = [
        go.Bar(
            x=df[column].value_counts().index,
            y=df[column].value_counts().values
        )
    ]

    fig = go.Figure(data=data)
    
    fig.update_layout(
        title_text=column,
        title_x=0.5,
        title_font_size=42,
        font_size=18)
    
    fig.update_layout(
        xaxis_title= column,
        yaxis_title="Number of counts",
    )
    fig.update_layout(template='plotly_dark')
    fig.show()

In [52]:
for col in renamed_df.columns:
    generate_plot(renamed_df, col)

The Dataset can be described with

In [12]:
renamed_df.value_counts()

Country_of_Origin  Producer                      Processing_Method
Colombia           La Plata                      Washed / Wet                 28
Brazil             Ipanema Agrícola SA           Natural / Dry                17
Thailand           Doi Tung Development Project  Washed / Wet                 12
Brazil             Ipanema Agricola S.A          Natural / Dry                11
Guatemala          ROBERTO MONTERROSO            Washed / Wet                 10
                                                                              ..
Indonesia          ANTON GAYO                    Natural / Dry                 1
                   MUDAR                         Other                         1
                   PT. Shriya Artha Nusantara    Washed / Wet                  1
                   SMALL HOLDERS FARMER          Semi-washed / Semi-pulped     1
Vietnam            Yeh, Li Chuan.                Other                         1
Length: 667, dtype: int64

In [46]:
counts_for_each_country = renamed_df["Country of origin"].value_counts() 
# create a mask, to filter all values above 30 and below 10 out
mask = country_counts.apply(lambda counts: 10 < counts < 30)
print(country_counts[mask_country_counts])

Uganda         26
Nicaragua      26
Kenya          25
El Salvador    21
Indonesia      20
China          16
Malawi         11
Name: Country_of_Origin, dtype: int64

In [62]:
prod_c = renamed_df["Producer"].value_counts()
print(producer_counts.index[0], producer_counts[0])
print(producer_counts.index[-1], producer_counts[-1])

La Plata 30
Exportadora de cafe condor s.a 1

In [61]:
pm_counts = renamed_df["Processing method"].value_counts(ascending=False)
print(pm_counts.index[0], pm_counts[0])
print(pm_counts.index[-1], pm_counts[-1])

Washed / Wet 812
Pulped natural / honey 14

In [13]:
renamed_df["Producer"]

0                                   METAD PLC
1                                   METAD PLC
2                                         NaN
3       Yidnekachew Dabessa Coffee Plantation
4                                   METAD PLC
                        ...
1306                 JUAN CARLOS GARCÍA LOPEZ
1307            COEB Koperativ Ekselsyo Basen
1308                          Teófilo Narváez
1309        WILLIAM ESTUARDO MARTINEZ PACHECO
1310                          Reinerio Zepeda
Name: Producer, Length: 1311, dtype: object