In [ ]:
import course;course.header()

## More advanced Pandas

In [1]:
import pandas as pd
pd.set_option("max_columns", 3000)

import numpy as np

In [2]:
df = pd.read_csv("../data/arabica_data_cleaned.csv", index_col=0)

In [3]:
df.loc[1, "Owner"]

'metad plc'

In [12]:
df.head()

,Country of Origin,Producer,Number.of.Bags,Processing Method,Aroma,Flavor,Aftertaste,Acidity,Body,Balance,Uniformity,Clean.Cup,Sweetness,Cupper.Points,Total.Cup.Points,Moisture,Category.One.Defects,Quakers,Category.Two.Defects,altitude_low_meters,altitude_high_meters,altitude_mean_meters
1,Ethiopia,METAD PLC,300,Washed / Wet,8.67,8.83,8.67,8.75,8.50,8.42,10.0,10.0,10.0,8.75,90.58,0.12,0,0.0,0,1950.0,2200.0,2075.0
2,Ethiopia,METAD PLC,300,Washed / Wet,8.75,8.67,8.50,8.58,8.42,8.42,10.0,10.0,10.0,8.58,89.92,0.12,0,0.0,1,1950.0,2200.0,2075.0
3,Guatemala,NaN,5,NaN,8.42,8.50,8.42,8.42,8.33,8.42,10.0,10.0,10.0,9.25,89.75,0.00,0,0.0,0,1600.0,1800.0,1700.0
4,Ethiopia,Yidnekachew Dabessa Coffee Plantation,320,Natural / Dry,8.17,8.58,8.42,8.42,8.50,8.25,10.0,10.0,10.0,8.67,89.00,0.11,0,0.0,2,1800.0,2200.0,2000.0
5,Ethiopia,METAD PLC,300,Washed / Wet,8.25,8.50,8.25,8.50,8.42,8.33,10.0,10.0,10.0,8.58,88.83,0.12,0,0.0,2,1950.0,2200.0,2075.0

# Dropping object columns

In [13]:
 df.dtypes.head()

Country of Origin     object
Producer              object
Number.of.Bags         int64
Processing Method     object
Aroma                float64
dtype: object

In [14]:
col_to_drop = []
for col, d in zip(df.columns, df.dtypes):
    if d == 'object':
        if col not in ["Country.of.Origin", "Producer", "Processing.Method"]:
            col_to_drop.append(col)
df.drop(columns=col_to_drop, inplace=True)

In [66]:
df

,Producer,Number.of.Bags,Aroma,Flavor,Aftertaste,Acidity,Body,Balance,Uniformity,Clean.Cup,Sweetness,Cupper.Points,Total.Cup.Points,Moisture,Category.One.Defects,Quakers,Category.Two.Defects,altitude_low_meters,altitude_high_meters,altitude_mean_meters,Aroma_bin,Aroma_cat
1,METAD PLC,300,8.67,8.83,8.67,8.75,8.50,8.42,10.00,10.00,10.00,8.75,90.58,0.12,0,0.0,0,1950.00,2200.00,2075.00,"(7.83, 8.75]",++
2,METAD PLC,300,8.75,8.67,8.50,8.58,8.42,8.42,10.00,10.00,10.00,8.58,89.92,0.12,0,0.0,1,1950.00,2200.00,2075.00,"(7.83, 8.75]",++
3,NaN,5,8.42,8.50,8.42,8.42,8.33,8.42,10.00,10.00,10.00,9.25,89.75,0.00,0,0.0,0,1600.00,1800.00,1700.00,"(7.83, 8.75]",++
4,Yidnekachew Dabessa Coffee Plantation,320,8.17,8.58,8.42,8.42,8.50,8.25,10.00,10.00,10.00,8.67,89.00,0.11,0,0.0,2,1800.00,2200.00,2000.00,"(7.83, 8.75]",++
5,METAD PLC,300,8.25,8.50,8.25,8.50,8.42,8.33,10.00,10.00,10.00,8.58,88.83,0.12,0,0.0,2,1950.00,2200.00,2075.00,"(7.83, 8.75]",++
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1307,JUAN CARLOS GARCÍA LOPEZ,12,7.08,6.83,6.25,7.42,7.25,6.75,10.00,0.00,10.00,6.75,68.33,0.11,0,0.0,20,900.00,900.00,900.00,"(-0.001, 7.33]",--
1308,COEB Koperativ Ekselsyo Basen,1,6.75,6.58,6.42,6.67,7.08,6.67,9.33,6.00,6.00,6.42,67.92,0.14,8,0.0,16,350.00,350.00,350.00,"(-0.001, 7.33]",--
1309,Teófilo Narváez,550,7.25,6.58,6.33,6.25,6.42,6.08,6.00,6.00,6.00,6.17,63.08,0.13,1,0.0,5,1100.00,1100.00,1100.00,"(-0.001, 7.33]",--
1310,WILLIAM ESTUARDO MARTINEZ PACHECO,275,7.50,6.67,6.67,7.67,7.33,6.67,8.00,1.33,1.33,6.67,59.83,0.10,0,0.0,4,1417.32,1417.32,1417.32,"(7.33, 7.5]",-
1312,Reinerio Zepeda,275,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.12,0,0.0,2,1400.00,1400.00,1400.00,"(-0.001, 7.33]",--

# renaming the dots

In [63]:
df.rename(
    columns={
        "Country.of.Origin": "Country of Origin", 
        "Producer": "Producer", 
        "Processing.Method": "Processing Method"
    },
    inplace=True
)

In [65]:
df

,Producer,Number.of.Bags,Aroma,Flavor,Aftertaste,Acidity,Body,Balance,Uniformity,Clean.Cup,Sweetness,Cupper.Points,Total.Cup.Points,Moisture,Category.One.Defects,Quakers,Category.Two.Defects,altitude_low_meters,altitude_high_meters,altitude_mean_meters,Aroma_bin,Aroma_cat
1,METAD PLC,300,8.67,8.83,8.67,8.75,8.50,8.42,10.00,10.00,10.00,8.75,90.58,0.12,0,0.0,0,1950.00,2200.00,2075.00,"(7.83, 8.75]",++
2,METAD PLC,300,8.75,8.67,8.50,8.58,8.42,8.42,10.00,10.00,10.00,8.58,89.92,0.12,0,0.0,1,1950.00,2200.00,2075.00,"(7.83, 8.75]",++
3,NaN,5,8.42,8.50,8.42,8.42,8.33,8.42,10.00,10.00,10.00,9.25,89.75,0.00,0,0.0,0,1600.00,1800.00,1700.00,"(7.83, 8.75]",++
4,Yidnekachew Dabessa Coffee Plantation,320,8.17,8.58,8.42,8.42,8.50,8.25,10.00,10.00,10.00,8.67,89.00,0.11,0,0.0,2,1800.00,2200.00,2000.00,"(7.83, 8.75]",++
5,METAD PLC,300,8.25,8.50,8.25,8.50,8.42,8.33,10.00,10.00,10.00,8.58,88.83,0.12,0,0.0,2,1950.00,2200.00,2075.00,"(7.83, 8.75]",++
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1307,JUAN CARLOS GARCÍA LOPEZ,12,7.08,6.83,6.25,7.42,7.25,6.75,10.00,0.00,10.00,6.75,68.33,0.11,0,0.0,20,900.00,900.00,900.00,"(-0.001, 7.33]",--
1308,COEB Koperativ Ekselsyo Basen,1,6.75,6.58,6.42,6.67,7.08,6.67,9.33,6.00,6.00,6.42,67.92,0.14,8,0.0,16,350.00,350.00,350.00,"(-0.001, 7.33]",--
1309,Teófilo Narváez,550,7.25,6.58,6.33,6.25,6.42,6.08,6.00,6.00,6.00,6.17,63.08,0.13,1,0.0,5,1100.00,1100.00,1100.00,"(-0.001, 7.33]",--
1310,WILLIAM ESTUARDO MARTINEZ PACHECO,275,7.50,6.67,6.67,7.67,7.33,6.67,8.00,1.33,1.33,6.67,59.83,0.10,0,0.0,4,1417.32,1417.32,1417.32,"(7.33, 7.5]",-
1312,Reinerio Zepeda,275,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.12,0,0.0,2,1400.00,1400.00,1400.00,"(-0.001, 7.33]",--

In [64]:
df['Processing Method'].value_counts()

KeyError: 'Processing Method'

In [17]:
df.sample(5)

,Producer,Number.of.Bags,Aroma,Flavor,Aftertaste,Acidity,Body,Balance,Uniformity,Clean.Cup,Sweetness,Cupper.Points,Total.Cup.Points,Moisture,Category.One.Defects,Quakers,Category.Two.Defects,altitude_low_meters,altitude_high_meters,altitude_mean_meters
1193,ANGEL DE LEON,50,7.58,7.67,7.42,7.42,7.67,7.67,8.67,8.67,8.67,7.67,79.08,0.10,0,0.0,1,1700.0000,1700.0000,1700.0000
214,DARY COLMAN ALVARADO VILLATORO,275,7.75,7.75,7.58,8.00,7.67,7.83,10.00,10.00,10.00,7.58,84.17,0.11,0,0.0,6,1116.7872,1116.7872,1116.7872
97,Kyagalanyi Coffee Ltd,200,8.17,7.92,7.75,7.75,7.67,7.75,10.00,10.00,10.00,8.00,85.00,0.11,0,0.0,1,1800.0000,1800.0000,1800.0000
813,Maria da Gloria Junqueira,53,7.58,7.50,7.17,7.50,7.50,7.42,10.00,10.00,10.00,7.33,82.00,0.12,0,0.0,2,950.0000,950.0000,950.0000
816,"AGRICOLA EL PILAR, S.A.",25,7.58,7.50,7.25,7.58,7.58,7.50,9.33,10.00,10.00,7.58,81.92,0.10,0,0.0,1,1901.0000,1901.0000,1901.0000

In [18]:
df.describe()

,Number.of.Bags,Aroma,Flavor,Aftertaste,Acidity,Body,Balance,Uniformity,Clean.Cup,Sweetness,Cupper.Points,Total.Cup.Points,Moisture,Category.One.Defects,Quakers,Category.Two.Defects,altitude_low_meters,altitude_high_meters,altitude_mean_meters
count,1311.000000,1311.000000,1311.000000,1311.000000,1311.000000,1311.000000,1311.000000,1311.000000,1311.00000,1311.000000,1311.000000,1311.000000,1311.000000,1311.000000,1310.000000,1311.000000,1084.000000,1084.000000,1084.000000
mean,153.887872,7.563806,7.518070,7.397696,7.533112,7.517727,7.517506,9.833394,9.83312,9.903272,7.497864,82.115927,0.088863,0.426392,0.177099,3.591915,1759.548954,1808.843803,1784.196379
std,129.733734,0.378666,0.399979,0.405119,0.381599,0.359213,0.406316,0.559343,0.77135,0.530832,0.474610,3.515761,0.047957,1.832415,0.840583,5.350371,8767.847252,8767.187498,8767.016913
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000
25%,14.500000,7.420000,7.330000,7.250000,7.330000,7.330000,7.330000,10.000000,10.00000,10.000000,7.250000,81.170000,0.090000,0.000000,0.000000,0.000000,1100.000000,1100.000000,1100.000000
50%,175.000000,7.580000,7.580000,7.420000,7.500000,7.500000,7.500000,10.000000,10.00000,10.000000,7.500000,82.500000,0.110000,0.000000,0.000000,2.000000,1310.640000,1350.000000,1310.640000
75%,275.000000,7.750000,7.750000,7.580000,7.750000,7.670000,7.750000,10.000000,10.00000,10.000000,7.750000,83.670000,0.120000,0.000000,0.000000,4.000000,1600.000000,1650.000000,1600.000000
max,1062.000000,8.750000,8.830000,8.670000,8.750000,8.580000,8.750000,10.000000,10.00000,10.000000,10.000000,90.580000,0.280000,31.000000,11.000000,55.000000,190164.000000,190164.000000,190164.000000

How to describe each Country.of.Origin separately?

In [19]:
df.groupby("Country of Origin").describe()

KeyError: 'Country of Origin'

# Aggregation and group operations!

In [20]:
grp = df[['Country of Origin','Body']].groupby("Country of Origin")

KeyError: "['Country of Origin'] not in index"

In [21]:
grp.head()

NameError: name 'grp' is not defined

Groups behave like dataframes or series!

In [22]:
grp.idxmax()

NameError: name 'grp' is not defined

**Note:** index is of original dataframe. Remember if not state explicitly, you will work on a view!

In [23]:
# get the content of a group object
grp.get_group('Vietnam')

NameError: name 'grp' is not defined

In [24]:
grp.mean()

NameError: name 'grp' is not defined

Groupby can also be combined

In [25]:
df[
    [
        'Country of Origin',
        'Body',
        'Aroma'
    ]
].groupby("Country of Origin").mean()

KeyError: "['Country of Origin'] not in index"

In [26]:
grp_cols = ['Country of Origin',"Processing Method"]
data_cols = ['Body','Aroma']
grp = df[grp_cols + data_cols].groupby(grp_cols)

KeyError: "['Processing Method', 'Country of Origin'] not in index"

In [27]:
grp.mean()

NameError: name 'grp' is not defined

## Interating using groupby

In [28]:
grp_cols = ['Country of Origin',"Processing Method"]
data_cols = ['Body','Aroma']
for name, grp in df[grp_cols + data_cols].groupby(grp_cols):
    print(name)
    display(grp)
    break

KeyError: "['Processing Method', 'Country of Origin'] not in index"

How to set Body for the first entry to 10?

In [29]:
grp_cols = ['Country of Origin',"Processing Method"]
data_cols = ['Body','Aroma']
for name, grp in df[grp_cols + data_cols].groupby(grp_cols):
    print(name)
    display(grp.iloc[0]["Body"])
    grp.iloc[0]["Body"] = 10
    break

KeyError: "['Processing Method', 'Country of Origin'] not in index"

In [30]:
grp_cols = ['Country of Origin',"Processing Method"]
data_cols = ['Body','Aroma']
for name, grp in df[grp_cols + data_cols].groupby(grp_cols):
    print(name)
    display(grp)
    break

KeyError: "['Processing Method', 'Country of Origin'] not in index"

How to fix it?

In [31]:
grp_cols = ['Country of Origin',"Processing Method"]
data_cols = ['Body','Aroma']
for name, grp in df[grp_cols + data_cols].groupby(grp_cols):
    print(name)
#     print()
    df.loc[grp.index[0], 'Body'] = 10
    display(grp)
    break

KeyError: "['Processing Method', 'Country of Origin'] not in index"

# more generic groupby and aggregation

In [32]:
grps = df.groupby(['Country of Origin',"Processing Method"])
# making is simpler - not defining data columns, ie keeping all

KeyError: 'Country of Origin'

In [33]:
grps.agg("mean")

NameError: name 'grps' is not defined

In [34]:
grps.max("mean")['Body']

NameError: name 'grps' is not defined

# Apply - Split - Combine
a very frequent usage of groupby

In [35]:
def top_x(df, x=7, col="Body"):
    return df.sort_values(col, ascending=False).head(x)

top_x(df)

,Producer,Number.of.Bags,Aroma,Flavor,Aftertaste,Acidity,Body,Balance,Uniformity,Clean.Cup,Sweetness,Cupper.Points,Total.Cup.Points,Moisture,Category.One.Defects,Quakers,Category.Two.Defects,altitude_low_meters,altitude_high_meters,altitude_mean_meters
15,Bazen Agricultural & Industrial Dev't Plc,300,8.25,8.33,8.50,8.25,8.58,8.75,9.33,10.0,9.33,8.50,87.83,0.05,0,0.0,2,1570.0,1700.0,1635.0
1,METAD PLC,300,8.67,8.83,8.67,8.75,8.50,8.42,10.00,10.0,10.00,8.75,90.58,0.12,0,0.0,0,1950.0,2200.0,2075.0
4,Yidnekachew Dabessa Coffee Plantation,320,8.17,8.58,8.42,8.42,8.50,8.25,10.00,10.0,10.00,8.67,89.00,0.11,0,0.0,2,1800.0,2200.0,2000.0
17,P.T. Toarco Jaya,1,8.33,8.25,7.83,7.75,8.50,8.42,10.00,10.0,10.00,8.33,87.42,0.03,0,0.0,0,1200.0,1800.0,1500.0
2,METAD PLC,300,8.75,8.67,8.50,8.58,8.42,8.42,10.00,10.0,10.00,8.58,89.92,0.12,0,0.0,1,1950.0,2200.0,2075.0
5,METAD PLC,300,8.25,8.50,8.25,8.50,8.42,8.33,10.00,10.0,10.00,8.58,88.83,0.12,0,0.0,2,1950.0,2200.0,2075.0
18,Green Gold Ethiopia | Phone: 0114342032,150,8.17,8.33,8.25,8.33,8.42,8.33,9.33,10.0,9.33,8.83,87.33,0.05,0,0.0,2,NaN,NaN,NaN

In [36]:
df.groupby(['Country of Origin',"Processing Method"]).apply(top_x)

KeyError: 'Country of Origin'

In [37]:
# passing args n kwargs to apply function
df.groupby(
    ['Country of Origin',"Processing Method"]
).apply(top_x, x=2)

KeyError: 'Country of Origin'

# Binning values
Pandas cut or pandas qcut!
* cut : cut an array by equal wide bins
* qcut : cut an array by equally populated bin

In [38]:
pd.cut(df.Aroma, 5) 
# note dot nomenclature (instead of df['Aroma']) only works if columns
# have no spaces

1            (7.0, 8.75]
2            (7.0, 8.75]
3            (7.0, 8.75]
4            (7.0, 8.75]
5            (7.0, 8.75]
              ...
1307         (7.0, 8.75]
1308         (5.25, 7.0]
1309         (7.0, 8.75]
1310         (7.0, 8.75]
1312    (-0.00875, 1.75]
Name: Aroma, Length: 1311, dtype: category
Categories (5, interval[float64]): [(-0.00875, 1.75] < (1.75, 3.5] < (3.5, 5.25] < (5.25, 7.0] < (7.0, 8.75]]

In [39]:
pd.qcut(df.Aroma, 5)

1         (7.83, 8.75]
2         (7.83, 8.75]
3         (7.83, 8.75]
4         (7.83, 8.75]
5         (7.83, 8.75]
             ...
1307    (-0.001, 7.33]
1308    (-0.001, 7.33]
1309    (-0.001, 7.33]
1310       (7.33, 7.5]
1312    (-0.001, 7.33]
Name: Aroma, Length: 1311, dtype: category
Categories (5, interval[float64]): [(-0.001, 7.33] < (7.33, 7.5] < (7.5, 7.67] < (7.67, 7.83] < (7.83, 8.75]]

In [40]:
df['Aroma_bin'] = pd.qcut(df.Aroma, 5)

In [41]:
df['Aroma_cat'] = pd.qcut(
    df.Aroma, 
    5, 
    labels=['--', '-', '', '+', '++']
)

In [42]:
df.head()

,Producer,Number.of.Bags,Aroma,Flavor,Aftertaste,Acidity,Body,Balance,Uniformity,Clean.Cup,Sweetness,Cupper.Points,Total.Cup.Points,Moisture,Category.One.Defects,Quakers,Category.Two.Defects,altitude_low_meters,altitude_high_meters,altitude_mean_meters,Aroma_bin,Aroma_cat
1,METAD PLC,300,8.67,8.83,8.67,8.75,8.50,8.42,10.0,10.0,10.0,8.75,90.58,0.12,0,0.0,0,1950.0,2200.0,2075.0,"(7.83, 8.75]",++
2,METAD PLC,300,8.75,8.67,8.50,8.58,8.42,8.42,10.0,10.0,10.0,8.58,89.92,0.12,0,0.0,1,1950.0,2200.0,2075.0,"(7.83, 8.75]",++
3,NaN,5,8.42,8.50,8.42,8.42,8.33,8.42,10.0,10.0,10.0,9.25,89.75,0.00,0,0.0,0,1600.0,1800.0,1700.0,"(7.83, 8.75]",++
4,Yidnekachew Dabessa Coffee Plantation,320,8.17,8.58,8.42,8.42,8.50,8.25,10.0,10.0,10.0,8.67,89.00,0.11,0,0.0,2,1800.0,2200.0,2000.0,"(7.83, 8.75]",++
5,METAD PLC,300,8.25,8.50,8.25,8.50,8.42,8.33,10.0,10.0,10.0,8.58,88.83,0.12,0,0.0,2,1950.0,2200.0,2075.0,"(7.83, 8.75]",++

In [43]:
df.groupby(
    ['Country of Origin',"Processing Method", "Aroma_cat"]
).apply(top_x, x=2).head(10)

KeyError: 'Country of Origin'

# Correlations based on Country of Origin

In [44]:
def correlate(grp, col_1="Aroma", col_2="Aroma"):
    return grp[col_1].corr(grp[col_2])

df.groupby(
    ['Country of Origin']
).apply(
    correlate, 
    col_1="Aroma", 
    col_2="Body"
).sort_values()

KeyError: 'Country of Origin'

In [45]:
def correlate(grp, col_1="Aroma", col_2="Aroma"):
    return grp[col_1].corr(grp[col_2]), grp.shape[0]  # how many obervations

df.groupby(
    ['Country of Origin']
).apply(
    correlate, 
    col_1="Aroma", 
    col_2="Body"
).sort_values()

KeyError: 'Country of Origin'

In [46]:
def correlate(grp, col_1="Aroma", col_2="Aroma"):
    return pd.Series(
        [
            grp[col_1].corr(grp[col_2]), 
            grp.shape[0]
        ], 
        index=['pearson-corr','n']
    )

df.groupby('Country of Origin').apply(
    correlate,  
    col_1="Aroma", 
    col_2="Body"
).sort_values('pearson-corr')

KeyError: 'Country of Origin'

# Pivot tables

In [47]:
df.shape

(1311, 22)

In [48]:
df.pivot_table(
    index=[
        "Country of Origin", 
        "Producer", 
        "Processing Method"
    ], 
    aggfunc=np.mean
)

KeyError: 'Country of Origin'

In [49]:
df.pivot_table(
    index=[
        "Processing Method",
        "Country of Origin", 
#         "Producer",  # will be dropped
    ], 
    aggfunc=np.mean
)

KeyError: 'Processing Method'

In [50]:
df.pivot_table(
    index=[
        "Processing Method",
        "Country of Origin", 
#         "Producer",  # will be dropped
    ], 
    aggfunc={
        'Aroma' : np.mean,
        'Body': np.max
    }
)

KeyError: 'Processing Method'

In [ ]:
df.pivot_table(
    index=[
        "Processing Method",
        "Country of Origin", 
#         "Producer",  # will be dropped
    ], 
    aggfunc=[np.median, np.mean]
)

In [51]:
idx = pd.IndexSlice

In [52]:
_df = df.pivot_table(
    index=[
        "Processing Method",
        "Country of Origin", 
#         "Producer",  # will be dropped
    ], 
    aggfunc=[np.median, np.mean, np.min, np.max]
)
_df.loc[
    idx[:,'Brazil'], 
    idx[:,['Acidity', 'Body']]
]

KeyError: 'Processing Method'

In [53]:
_df.loc[
    idx['Natural / Dry',:], 
    idx['median',['Acidity', 'Body']]
].head(5)

NameError: name '_df' is not defined

## Backup

In [54]:
df.sort_values("Total.Cup.Points", ascending=False).head(1)

,Producer,Number.of.Bags,Aroma,Flavor,Aftertaste,Acidity,Body,Balance,Uniformity,Clean.Cup,Sweetness,Cupper.Points,Total.Cup.Points,Moisture,Category.One.Defects,Quakers,Category.Two.Defects,altitude_low_meters,altitude_high_meters,altitude_mean_meters,Aroma_bin,Aroma_cat
1,METAD PLC,300,8.67,8.83,8.67,8.75,8.5,8.42,10.0,10.0,10.0,8.75,90.58,0.12,0,0.0,0,1950.0,2200.0,2075.0,"(7.83, 8.75]",++

In [55]:
df['Country.of.Origin'].unique()

KeyError: 'Country.of.Origin'

In [56]:
df['altitude_mean_meters'].describe()

count      1084.000000
mean       1784.196379
std        8767.016913
min           1.000000
25%        1100.000000
50%        1310.640000
75%        1600.000000
max      190164.000000
Name: altitude_mean_meters, dtype: float64

In [57]:
df.sort_values('altitude_mean_meters', ascending=False).head(10)

,Producer,Number.of.Bags,Aroma,Flavor,Aftertaste,Acidity,Body,Balance,Uniformity,Clean.Cup,Sweetness,Cupper.Points,Total.Cup.Points,Moisture,Category.One.Defects,Quakers,Category.Two.Defects,altitude_low_meters,altitude_high_meters,altitude_mean_meters,Aroma_bin,Aroma_cat
897,"AGRICOLA EL PILAR, SA.",25,7.42,7.42,7.08,7.50,7.42,7.33,10.00,10.00,10.00,7.42,81.58,0.12,0,0.0,0,190164.0,190164.0,190164.0,"(7.33, 7.5]",-
1145,"AGRICOLA EL PILAR, S.A.",25,7.50,7.42,7.25,7.58,7.33,7.42,9.33,9.33,9.33,7.25,79.75,0.10,0,4.0,1,190164.0,190164.0,190164.0,"(7.33, 7.5]",-
1041,ROLANDO LACAYO,275,7.25,7.25,7.17,7.25,7.33,7.25,10.00,10.00,10.00,7.25,80.75,0.12,0,0.0,5,110000.0,110000.0,110000.0,"(-0.001, 7.33]",--
544,GERSON NAIMEG,300,7.08,7.50,7.50,7.83,7.75,7.67,10.00,10.00,10.00,7.58,82.92,0.11,0,0.0,16,11000.0,11000.0,11000.0,"(-0.001, 7.33]",--
1099,U Htun Htun,1,7.42,7.00,7.08,7.00,7.17,7.33,10.00,10.00,10.00,7.25,80.25,0.00,0,0.0,1,4287.0,4287.0,4287.0,"(7.33, 7.5]",-
841,U Mg Mg,1,7.33,7.58,7.50,7.42,7.33,7.33,10.00,10.00,10.00,7.33,81.83,0.00,0,0.0,2,4001.0,4001.0,4001.0,"(-0.001, 7.33]",--
629,Mariana Cabrera Pantoja; I.D.: 27 423 625,1,7.33,7.58,7.42,7.42,7.67,7.67,10.00,10.00,10.00,7.58,82.67,0.11,0,0.0,0,1800.0,5900.0,3850.0,"(-0.001, 7.33]",--
1124,Ngu Shwe Li Coffee Estate,1,7.17,7.33,7.00,7.42,7.17,7.00,10.00,10.00,10.00,6.92,80.00,0.00,0,0.0,4,3845.0,3845.0,3845.0,"(-0.001, 7.33]",--
1039,U Soe,1,6.92,7.50,7.00,7.58,7.50,7.08,10.00,10.00,10.00,7.17,80.75,0.00,0,0.0,2,3825.0,3825.0,3825.0,"(-0.001, 7.33]",--
1074,Shwe Yin Mar,1,7.17,7.33,7.17,7.42,7.25,7.08,10.00,10.00,10.00,7.08,80.50,0.00,0,0.0,2,3800.0,3800.0,3800.0,"(-0.001, 7.33]",--

# Visualizing distribution of altitude

In [58]:
data = []
for name, grp in df.groupby("Country.of.Origin"):
    data.append(go.Histogram(x=grp['altitude_mean_meters'], name=name))
fig = go.Figure(data=data)
fig.show()

KeyError: 'Country.of.Origin'

# Reviews

In [59]:
df.columns

Index(['Producer', 'Number.of.Bags', 'Aroma', 'Flavor', 'Aftertaste',
       'Acidity', 'Body', 'Balance', 'Uniformity', 'Clean.Cup', 'Sweetness',
       'Cupper.Points', 'Total.Cup.Points', 'Moisture', 'Category.One.Defects',
       'Quakers', 'Category.Two.Defects', 'altitude_low_meters',
       'altitude_high_meters', 'altitude_mean_meters', 'Aroma_bin',
       'Aroma_cat'],
      dtype='object')

In [60]:
rcols = [
    'Aroma', 
    'Flavor', 
    'Aftertaste', 
    'Acidity', 
    'Body',
#     'Balance', 
#     'Uniformity', 
#     'Clean.Cup', 
#     'Sweetness', 
    'Cupper.Points'
]

In [61]:
import numpy as np
data = []
for name, grp in df.groupby("Country.of.Origin"):
    s1 = grp[rcols].apply(np.max, axis=0)
    data.append(
        go.Scatterpolar(
          r=s1,
          theta=rcols,
#           fill='toself',
          name=name
        )
    )
fig = go.Figure(data=data)
fig.show()

KeyError: 'Country.of.Origin'